[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps =
    fastled/FastLED@3.9.7
    bblanchon/ArduinoJson@^7.0.0
    ESP32Async/AsyncTCP@^3.3.2
    ESP32Async/ESPAsyncWebServer@^3.6.0
    WiFi
    solnera/ESP32-MCPServer@^0.2.1
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = default.csv
upload_protocol = esptool
build_unflags = -std=gnu++11
build_flags = 
    -std=gnu++17
    -D CORE_DEBUG_LEVEL=3
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=0
