#!/usr/bin/env bash
#
# Line-coverage report for the native test suite.
#
#   scripts/coverage.sh [min-percent]     # default 80
#
# Builds and runs env:native-cov, then folds the accumulated .gcda into a
# per-file summary. Only src/ and include/ are counted — the mocks under
# test/mock and ArduinoJson are not ours to cover. All five test programs link
# the same instrumented src/ objects, so their .gcda counts merge into a single
# union across the whole suite.
#
# Exits non-zero if total line coverage is below the threshold.

set -euo pipefail

cd "$(dirname "$0")/.."
REPO="$PWD"
BUILD=".pio/build/native-cov"
THRESHOLD="${1:-80}"

# Stale counts from a previous run would inflate the result; the .gcno are
# regenerated by the build itself.
find "$BUILD" -name '*.gcda' -delete 2>/dev/null || true

echo "==> pio test -e native-cov"
pio test -e native-cov 2>&1 | tail -12

# Apple ships llvm-cov's gcov emulation behind xcrun and no standalone gcov
# that understands clang's .gcno; GNU toolchains have the real thing. Both
# accept -t (stream to stdout).
if command -v xcrun >/dev/null 2>&1 && xcrun --find llvm-cov >/dev/null 2>&1; then
    GCOV=(xcrun llvm-cov gcov)
elif command -v gcov >/dev/null 2>&1; then
    # PlatformIO's native platform uses the host GNU toolchain by default on
    # Linux. GitHub runners also carry LLVM, so prefer the matching GNU reader
    # when both are on PATH; llvm-cov is not guaranteed to understand gcno/gcda
    # emitted by current GCC releases.
    GCOV=(gcov)
elif command -v llvm-cov >/dev/null 2>&1; then
    GCOV=(llvm-cov gcov)
else
    echo "no gcov/llvm-cov on PATH" >&2
    exit 1
fi

shopt -s nullglob
# Test objects are included so that inline code in our headers counts as
# covered when it is exercised from a test. The src/+include/ filter below
# still keeps the test sources themselves out of the score.
GCDA=("$BUILD"/src/*.gcda "$BUILD"/test/*/*.gcda)
if [ ${#GCDA[@]} -eq 0 ]; then
    echo "no .gcda produced under $BUILD — did the build run?" >&2
    exit 1
fi

# Paths recorded in the .gcda are relative to the compilation directory, so
# gcov has to run from the repo root to resolve sources. -t streams every file
# to stdout (delimited by the Source: headers we parse below) instead of
# littering the tree with .gcov files.
#
# Pass 1 emits one "<file> <covered> <total>" record per source file we own.
#
# Coverage is merged per (file, line) rather than accumulated per block: a
# header is compiled into every translation unit that includes it, so
# MCPServer.h shows up once per .gcda with different counts each time. Summing
# those would count each header line several times and score a line covered in
# one TU but not another as both. Taking the max per line is what gcov itself
# does when merging runs.
#
# Sorting and totalling happen downstream so this stays portable to BSD awk
# (no asorti).
"${GCOV[@]}" -t "${GCDA[@]}" 2>/dev/null | awk '
    # The Source: header decides whether the following block belongs to us.
    /^ *-: *0:Source:/ {
        src = $0; sub(/^.*Source:/, "", src)
        keep = (index(src, "src/") == 1 || index(src, "include/") == 1)
        if (keep) { name = src; sub(/^.*\//, "", name) }
        next
    }
    !keep { next }
    {
        split($0, a, ":")
        count = a[1]; gsub(/ /, "", count)
        line = a[2] + 0
        if (line == 0 || count == "-") next     # header or non-executable line
        key = name SUBSEP line
        owner[key] = name
        if (count == "#####") { if (!(key in hit)) hit[key] = 0 }
        else                  { hit[key] = 1 }
    }
    END {
        for (k in hit) { total[owner[k]]++; covered[owner[k]] += hit[k] }
        for (f in total) printf "%s %d %d\n", f, covered[f], total[f]
    }
' | sort | awk -v threshold="$THRESHOLD" '
    BEGIN {
        printf "%-24s %9s %7s %8s\n", "FILE", "COVERED", "TOTAL", "PCT"
        for (i = 0; i < 52; i++) printf "-"; printf "\n"
    }
    { gc += $2; gt += $3; printf "%-24s %9d %7d %7.1f%%\n", $1, $2, $3, 100.0 * $2 / $3 }
    END {
        for (i = 0; i < 52; i++) printf "-"; printf "\n"
        pct = gt ? 100.0 * gc / gt : 0
        printf "%-24s %9d %7d %7.1f%%\n", "TOTAL", gc, gt, pct
        printf "\nthreshold %s%% -> %s\n", threshold, (pct + 0 < threshold + 0 ? "FAIL" : "PASS")
        exit (pct + 0 < threshold + 0) ? 1 : 0
    }
'
